#!/bin/sh
# ci_post_clone.sh — Xcode Cloud post-clone script.
#
# Generates Config/Local.xcconfig from Xcode Cloud environment variables so
# the cloud build picks up private signing and project identity values without
# those values ever being committed to the repo. The API key is compiled into
# the app's Info.plist; use only a restricted, revocable demo key.
#
# Required Xcode Cloud environment variables (set in App Store Connect):
#   FINANCE_DEMO_BUNDLE_ID    — e.g. com.yourcompany.MetabindFinanceDemo
#   FINANCE_DEMO_ORG_ID       — Metabind org ID for your project
#   FINANCE_DEMO_PROJECT_ID   — Metabind project ID
#   FINANCE_DEMO_API_KEY      — API key for the private demo build
#   DEVELOPMENT_TEAM          — Apple Developer team ID (10-character string)
#
# This script runs before the build, so the generated file is available when
# Xcode resolves the xcconfig include chain.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
CONFIG_DIR="$SCRIPT_DIR/../Config"
LOCAL_XCCONFIG="$CONFIG_DIR/Local.xcconfig"

# Validate that required variables are present.
: "${FINANCE_DEMO_BUNDLE_ID:?FINANCE_DEMO_BUNDLE_ID must be set in Xcode Cloud environment variables}"
: "${FINANCE_DEMO_ORG_ID:?FINANCE_DEMO_ORG_ID must be set in Xcode Cloud environment variables}"
: "${FINANCE_DEMO_PROJECT_ID:?FINANCE_DEMO_PROJECT_ID must be set in Xcode Cloud environment variables}"
: "${FINANCE_DEMO_API_KEY:?FINANCE_DEMO_API_KEY must be set in Xcode Cloud environment variables}"
: "${DEVELOPMENT_TEAM:?DEVELOPMENT_TEAM must be set in Xcode Cloud environment variables}"

mkdir -p "$CONFIG_DIR"

cat > "$LOCAL_XCCONFIG" <<EOF
// Generated by ci_post_clone.sh — do not edit by hand.
FINANCE_DEMO_BUNDLE_ID = ${FINANCE_DEMO_BUNDLE_ID}
FINANCE_DEMO_ORG_ID = ${FINANCE_DEMO_ORG_ID}
FINANCE_DEMO_PROJECT_ID = ${FINANCE_DEMO_PROJECT_ID}
FINANCE_DEMO_API_KEY = ${FINANCE_DEMO_API_KEY}
DEVELOPMENT_TEAM = ${DEVELOPMENT_TEAM}
EOF

echo "ci_post_clone: wrote Local.xcconfig"
