// GENERATED by `metabind pull` — do not edit.
//
// Local declarations covering known gaps in the vendored BindJS types. Each one
// is a candidate fix upstream in metabindai/bindjs-runtime; when a fix lands and
// the vendored types are refreshed, the matching shim here becomes redundant and
// should be removed.

declare global {
  /**
   * Root-slot placeholder. Present in the runtime, absent from the published
   * types.
   */
  function Self(children?: unknown): unknown;
}

export {};
