// Generated by `metabind pull` — do not edit.
// Typed globals for this project's own components, so a cross-component call gets
// real prop types instead of `any`. Regenerated on every pull.

declare global {
  interface ProjectComponents {
  /**
   * Net worth history plus the account balances behind it: the range-end total, the change over the range, a value series at an auto-picked granularity, and per-account balances. `income`/`spending`/`saved` break the change down for the same range — net worth here is accumulated cash flow, so `saved` accounts for essentially all of it. Answer "what drove the change" from that and from spending categories, never from the account balances: their shares are fixed proportions and attribute nothing. Pass a period, or startDate/endDate (YYYY-MM-DD) for an arbitrary range — dates override the period. Call this only when you need the numbers to reason with; to DISPLAY net worth, call net_worth_trend with the period instead — it loads this itself.
   * Properties could not be read from source.
   */
  GetNetWorth: (props?: { [key: string]: any }, children?: Component[]) => Component;
  /**
   * Spending by category for a period — each category's amount, share, transaction count, change from the prior period, and top merchants, plus the totals and the overall change. Call this only when you need the numbers to reason with; to DISPLAY spending, call spending_breakdown with the period instead — it loads this itself.
   * Properties could not be read from source.
   */
  GetSpendingBreakdown: (props?: { [key: string]: any }, children?: Component[]) => Component;
  /**
   * Recurring charges detected in the transaction feed: each subscription's amount, cadence, next charge date, normalized monthly cost, and flags for newly added subscriptions and recent price increases, plus the total monthly spend. Status 'active' (default) lists current subscriptions; 'all' also includes recently cancelled ones. Call this only when you need the numbers to reason with; to DISPLAY subscriptions, call the subscriptions card instead — it loads this itself.
   * Properties could not be read from source.
   */
  GetSubscriptions: (props?: { [key: string]: any }, children?: Component[]) => Component;
  /**
   * Raw transactions for a category or a single merchant, with the window total, count, and change vs the prior window. Categories: Housing, Food & Dining, Groceries, Shopping, Transportation, Entertainment, Subscriptions, Utilities, Health, Income — plain terms like 'restaurants', 'rent', 'gas' or 'paycheck' resolve, as does a merchant name in the category slot. Omit both for all spending (income is excluded from spending totals; ask for the Income category to see deposits). Any category- or merchant-scoped query returns that window's line items rolled up biggest-first (`top_items`) — which is what answers "what should I stop buying"; merchant-scoped queries additionally itemise each row's basket. Every row carries `vs_typical_pct` (this charge against what that merchant normally costs), and `standouts` lists the few charges furthest above typical across the whole window — use it for "anything unusual" rather than scanning rows. Pass sort:'largest' for biggest-first. Covers roughly the past 25 months. Call this only when you need the numbers to reason with; to DISPLAY transactions, call transaction_list with the filter instead — it loads this itself.
   * Properties could not be read from source.
   */
  GetTransactions: (props?: { [key: string]: any }, children?: Component[]) => Component;
  /**
   * Net worth: current total, change over the period, a trend chart, and the account balances behind it. It loads its own data. Set chartStyle='bar' to compare month-end balances instead of drawing the continuous line.
   * Properties: endDate, period, groupBy, nextSteps, chartStyle, startDate, note
   */
  NetWorthTrend: (props?: { endDate?: string; period?: string; groupBy?: "auto" | "day" | "week" | "month" | "quarter" | "year"; nextSteps?: unknown[]; chartStyle?: "line" | "bar"; startDate?: string; note?: string }, children?: Component[]) => Component;
  /**
   * Spending split by category for a period: a composition bar plus a ranked category list. It loads its own data — pass the period alone for the whole picture, which is what a broad 'where did my money go' question wants. `highlight` is for follow-ups about particular categories only; see its own description.
   * Properties: period, highlight, note, drillPrompt, nextSteps
   */
  SpendingBreakdown: (props?: { period?: string; highlight?: unknown[]; note?: string; drillPrompt?: string; nextSteps?: unknown[] }, children?: Component[]) => Component;
  /**
   * Recurring charges: total monthly cost and a row per subscription with its cadence, next charge date, and New / price-increase flags. It loads its own data.
   * Properties: nextSteps, view, status, views, note
   */
  Subscriptions: (props?: { nextSteps?: unknown[]; view?: "all" | "unusual" | "new" | "repriced"; status?: "active" | "all"; views?: unknown[]; note?: string }, children?: Component[]) => Component;
  /**
   * Individual purchases for a category or a merchant: the window total plus the matching transactions. It loads its own data. Plain terms like 'restaurants', 'groceries' or 'gas' resolve to categories; omit both filters for all spending.
   * Properties: nextSteps, startDate, category, endDate, limit, period, view, views, merchant, note
   */
  TransactionList: (props?: { nextSteps?: unknown[]; startDate?: string; category?: string; endDate?: string; limit?: number; period?: string; view?: "recent" | "largest" | "unusual"; views?: unknown[]; merchant?: string; note?: string }, children?: Component[]) => Component;
  /**
   * Any metric over time that has no dedicated card — one category's spend by month, a series you computed. Points are {label, value} in display order. Set upIsGood=false for cost-like metrics. chartStyle='bar' compares discrete periods; give each point a `series` name (repeating the label once per series) to stack them with a legend. Pass `items` to list the composition behind the number.
   * Properties: note, valueFormat, nextSteps, change_pct, current, periodLabel, start, upIsGood, items, points, title, valueSuffix, change, chartStyle
   */
  TrendCard: (props?: { note?: string; valueFormat?: "currency" | "number"; nextSteps?: unknown[]; change_pct?: number; current?: number; periodLabel?: string; start?: number; upIsGood?: boolean; items?: unknown[]; points?: unknown[]; title?: string; valueSuffix?: string; change?: number; chartStyle?: "line" | "bar" }, children?: Component[]) => Component;
  }

  const GetNetWorth: (props?: { [key: string]: any }, children?: Component[]) => Component;
  const GetSpendingBreakdown: (props?: { [key: string]: any }, children?: Component[]) => Component;
  const GetSubscriptions: (props?: { [key: string]: any }, children?: Component[]) => Component;
  const GetTransactions: (props?: { [key: string]: any }, children?: Component[]) => Component;
  const NetWorthTrend: (props?: { endDate?: string; period?: string; groupBy?: "auto" | "day" | "week" | "month" | "quarter" | "year"; nextSteps?: unknown[]; chartStyle?: "line" | "bar"; startDate?: string; note?: string }, children?: Component[]) => Component;
  const SpendingBreakdown: (props?: { period?: string; highlight?: unknown[]; note?: string; drillPrompt?: string; nextSteps?: unknown[] }, children?: Component[]) => Component;
  const Subscriptions: (props?: { nextSteps?: unknown[]; view?: "all" | "unusual" | "new" | "repriced"; status?: "active" | "all"; views?: unknown[]; note?: string }, children?: Component[]) => Component;
  const TransactionList: (props?: { nextSteps?: unknown[]; startDate?: string; category?: string; endDate?: string; limit?: number; period?: string; view?: "recent" | "largest" | "unusual"; views?: unknown[]; merchant?: string; note?: string }, children?: Component[]) => Component;
  const TrendCard: (props?: { note?: string; valueFormat?: "currency" | "number"; nextSteps?: unknown[]; change_pct?: number; current?: number; periodLabel?: string; start?: number; upIsGood?: boolean; items?: unknown[]; points?: unknown[]; title?: string; valueSuffix?: string; change?: number; chartStyle?: "line" | "bar" }, children?: Component[]) => Component;
}

export {};
