// Generated by `metabind pull` — do not edit.
// `env.secrets` typed to the names this project binds. An unknown name is a
// compile error rather than a failure that surfaces when a tool runs.

declare global {
  namespace env {
    const secrets: {
      readonly [key: string]: never;
    };
  }
}

export {};
